### PR TITLE
WIP: Paragraph as node description

### PR DESCRIPTION
**Pull request by Kibouo**
Hi! I've been working on #28 the last few days. If a "thing" turns into a node, then the paragraph *after* it is added as a description.

This is how it looks for now: image

Some things to note:
- I'm *not* a designer. I've simply tried to replicate the style mentioned in #28 (grey arrow to toggle description). If anyone has a nicer design in mind, please say so!

- Bug: some images are cut off if they're used as description. I haven't found the reason for this yet image

- Todo: when pressing the arrow to hide the description, the description disappears without animation. I do not know how to add a transition to it. Could you help with this @gera2ld? The HTMLParagraphElement with the `.description` class should have a transition when being removed.

P.S.: single character node properties make the code hard to read :(

### CODE REVIEW

**Comment by gera2ld** [comment]
Hi @Kibouo, thanks for the great work. I love the description idea.

But I still have a couple of questions.

- How to decide if an element should be a node?
  I don't think the content following a paragraph is always the description of it. Maybe better for every element to become a node?
- How to deal with the description node and the sub-headings below it? e.g.
    ```md
    # heading 1
    a list:
    - 1
    - 2
    and some headings:

    ## heading 1.1
    blabla
    ## heading 1.2
    blabla
    ```
- The previous question can be solved if we render description in a block and allow sub tree from nodes in description block. But here comes a new question: how to support sub-trees from description block?
  In that case we will have to implement multiple output ports first, one for the sub-headings, and others for those from description.

Here is a schematic diagram roughly representing what I mean:

markmap

Maybe it's overcomplex but I couldn't find a better way to support lists and sub-headings at the same time.

> P.S.: single character node properties make the code hard to read :(

That's true, I'm gonna change this some day.

**Comment by Kibouo** [comment]
Do I understand correctly that you are trying to solve #80?

> The previous question can be solved if we render description in a block and allow sub tree from nodes in description block.
A sub-tree is not a bad idea, but...

> Maybe it's overcomplex but I couldn't find a better way to support lists and sub-headings at the same time.
Yes, the diagram looks complex. A complex diagram can be confusing.

Maybe it is easier to choose a design for the sub-tree with a testing prototype?

**Comment by Lukortech** [comment]
I would very much love to see this merged, it'd be helpful at our company. 
Is there any way I could contribute? I can see there's no convo for a month now.

**Comment by vipzhicheng** [comment]
For the effect, I don't like to show description under the item, I suggest adding an icon along with the item, when clicking it, popup the description.

**Comment by haenter** [comment]
It seems a related bug or enhancement so I comment here on the problem that might be solved in the future instead of opening a new issue. lists are not rendered correctly, an example is as follows:

# Root

## Child 1
- Grand Child 1
- - Child 1 of the Grand Child 1
- - Child 2 of the Grand Child 1
- - Child 3 of the Grand Child 1
- - Child 4 of the Grand Child 1
- Grand Child 2
- Grand Child 3
- Grand Child 4

## Child 2

## Child 3
## Child 4

**Comment by gera2ld** [comment]
Closing as paragraphs are now supported.
Thanks for your effort.

**Pull request closed without merging**
